<?php

namespace AppBundle\Repository;

/**
 * AccessCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessCodesRepository extends \Doctrine\ORM\EntityRepository
{
}
