<?php

namespace AppBundle\Repository;

/**
 * AlignmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlignmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
