<?php

namespace AppBundle\Repository;

/**
 * CharacterSkillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSkillsRepository extends \Doctrine\ORM\EntityRepository
{
}
