<?php

namespace AppBundle\Repository;

/**
 * ClassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassesRepository extends \Doctrine\ORM\EntityRepository
{
}
