<?php

namespace AppBundle\Repository;

/**
 * DailySpellsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailySpellsRepository extends \Doctrine\ORM\EntityRepository
{
}
