<?php

namespace AppBundle\Repository;

/**
 * DeitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
