<?php

namespace AppBundle\Repository;

/**
 * FeatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatsRepository extends \Doctrine\ORM\EntityRepository
{
}
