<?php

namespace AppBundle\Repository;

/**
 * MoneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoneyRepository extends \Doctrine\ORM\EntityRepository
{
}
