<?php

namespace AppBundle\Repository;

/**
 * MonstersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonstersRepository extends \Doctrine\ORM\EntityRepository
{
}
