<?php

namespace AppBundle\Repository;

/**
 * RacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RacesRepository extends \Doctrine\ORM\EntityRepository
{
}
