<?php

namespace AppBundle\Repository;

/**
 * SkillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillsRepository extends \Doctrine\ORM\EntityRepository
{
}
