<?php

namespace AppBundle\Repository;

/**
 * SpecialAbilitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialAbilitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
