<?php

namespace AppBundle\Repository;

/**
 * SpellsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpellsRepository extends \Doctrine\ORM\EntityRepository
{
}
