<?php

namespace AppBundle\Repository;

/**
 * StatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModifier(int $value) {
        return floor(($value - 10) / 2);
    }
}
