<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsRepository extends EntityRepository
{
    public function getModifier(int $id, string $stat): int
    {
        $orv_getter = 'get' . ucfirst($stat);
        $tmp_getter = "{$orv_getter}Temp";
        $original_value = $this->find($id)->{$orv_getter}();
        $temp_value = $this->find($id)->{$tmp_getter}();
        return (int) floor((($original_value + $temp_value) - 10) / 2);
    }

    public function getAC(int $id) : int
    {
        $stat = $this->find($id);
        $armor_bonus = $stat->getArmorBonus();
        $shield_bonus = $stat->getShieldBonus();
        $dex_modifier = self::getModifier($id, 'dexterity');
        $size_modifier = $stat->getSizeModifier();
        return $armor_bonus + $shield_bonus + $dex_modifier + $size_modifier +
    }
}
