<?php

namespace AppBundle\Repository;

/**
 * WeaponsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponsRepository extends \Doctrine\ORM\EntityRepository
{
}
